[[redirects]]
    from = "/"
    to = "https://github.com/andrejarrell"
[[redirects]]
    from = "/digitalocean"
    to = "https://m.do.co/c/6aef79a2cf4a"
[[redirects]]
    from = "/instagram"
    to = "https://www.instagram.com/andrejarrell"
[[redirects]]
    from = "/linkedin"
    to = "https://www.linkedin.com/in/andrejarrell"