[build]
    publish = "site"
[build.processing.css]
    bundle = true
    minify = true
[build.processing.js]
    bundle = true
    minify = true
[[redirects]]
    from = "/github"
    to = "https://github.com/andrejarrell"
[[redirects]]
    from = "/linkedin"
    to = "https://www.linkedin.com/in/andrejarrell"
[[redirects]]
    from = "/reddit"
    to = "https://www.reddit.com/user/andrejarrell"
[[redirects]]
    from = "/digitalocean"
    to = "https://m.do.co/c/6aef79a2cf4a"
[[redirects]]
    from = "/glitch"
    to = "https://glitch.com/@andrejarrell"
[[redirects]]
    from = "/instagram"
    to = "https://www.instagram.com/andrejarrell"