[build]
    publish = "site"
[build.processing.css]
    bundle = true
    minify = true
[build.processing.js]
    bundle = true
    minify = true
[[redirects]]
    from = "/github"
    to = "https://github.com/andrejarrell"
[[redirects]]
    from = "/digitalocean"
    to = "https://m.do.co/c/6aef79a2cf4a"
[[redirects]]
    from = "/instagram"
    to = "https://www.instagram.com/andrejarrell"
[[redirects]]
    from = "/youtube"
    to = "https://www.youtube.com/channel/UC905N0PraDnnIDIB2cqL74Q"