name: Show Dev Posts
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: andrejarrell/devposts@master
        with:
          posts_feed: https://dev.to/feed/andrejarrell
          github_token: ${{ secrets.GH_TOKEN }}