name: Show Dev Posts
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: andrejarrell/devposts@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          posts_amount: 10
          posts_feed: https://dev.to/feed/andrejarrell
          commit_username: andrejarrell's action
          commit_email: action@andrejarrell.com