name: Update Dev Posts
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env: 
  FEED: https://dev.to/feed/andrejarrell
  MESSAGE: Updated Dev Posts
  USERNAME: andrejarrell's workflow
  EMAIL: mail@andrejarrell.com
  LOCATOR: <!-- posts -->
  TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with: 
        node-version: 12
      - run: npm ci
      - run: npm run posts